# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    # Use ["main", "master"] for CI only on the default branch.
    # Use ["**"] for CI on all branches.
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (official GitHub action)
        uses: actions/checkout@v4
        with:
          # Important for versioning plugins:
          fetch-depth: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"
          enable-cache: true
          python-version: "3.11"

      - name: Set up Python (using uv)
        run: uv python install

      - name: Install all dependencies
        run: uv sync --all-extras --dev

      - name: Run linting
        run: uv run python devtools/lint.py

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (official GitHub action)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"
          enable-cache: true
          python-version: "3.11"

      - name: Set up Python (using uv)
        run: uv python install

      - name: Install all dependencies
        run: uv sync --all-extras --dev

      - name: Run type checking
        run: uv run basedpyright

  test:
    strategy:
      matrix:
        # Update this as needed:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    # Linux only by default. Use ${{ matrix.os }} for other OSes.
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (official GitHub action)
        uses: actions/checkout@v4
        with:
          # Important for versioning plugins:
          fetch-depth: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          # Update this as needed:
          version: "0.6.14"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Set up Python (using uv)
        run: uv python install

      - name: Install all dependencies
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        run: uv run pytest --cov=src/dataflow --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (official GitHub action)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"
          enable-cache: true
          python-version: "3.11"

      - name: Set up Python (using uv)
        run: uv python install

      - name: Install all dependencies
        run: uv sync --all-extras --dev

      - name: Build documentation
        run: uv run mkdocs build
