name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - ".github/workflows/docker-build.yml"
      - "src/**"
  pull_request:
    branches: [main]
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - ".github/workflows/docker-build.yml"
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          target: api
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dataflow-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dataflow-api:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dataflow-api:latest
          cache-to: type=inline

      - name: Build and push Dagster image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          target: dagster
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dataflow-dagster:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dataflow-dagster:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dataflow-dagster:latest
          cache-to: type=inline
